// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.Effects = (function() {

    function Effects() {
      this.hover = __bind(this.hover, this);
      $('.downloadable').live('mouseover', this.hover);
    }

    Effects.prototype.hover = function(event) {
      var single;
      single = $(event.currentTarget);
      $('.downloadable').addClass('blurred');
      return single.removeClass('blurred');
    };

    return Effects;

  })();

}).call(this);
